apiVersion: kind.x-k8s.io/v1alpha4
name: alura-kubernetes
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/bruna/alura-kubernetes
        containerPath: /alura-kubernetes